### ISSUE TITLE
missing fstab file

### ISSUE THREAD

**Issue by kitten77** [iocage/iocage#128]
[webhotell_env] root@firestar:/iocage/jails # iocage -v
Version 0.9.8 BETA

[webhotell_env] root@firestar:/iocage/jails # iocage list
+-----+----------+-------+----------------------------+--------------+-------------+
| JID |   UUID   | STATE |            TAG             |   RELEASE    |     IP4     |
+=====+==========+=======+============================+==============+=============+
| -   | 743f1941 | down  | 2017-05-11@09:19:46:636029 | 11.0-RELEASE | -           |
+-----+----------+-------+----------------------------+--------------+-------------+
| 1   | 9dc087fe | up    | tom                        | 11.0-RELEASE | 10.0.10.200 |
+-----+----------+-------+----------------------------+--------------+-------------+
[webhotell_env] root@firestar:/iocage/jails # iocage destroy  2017-05-11@09:19:46:636029

This will destroy jail 743f1941-20e2-4df5-abf5-e4138d823ba6 (2017-05-11@09:19:46:636029)

Are you sure? [y/N]: y
[webhotell_env] root@firestar:/iocage/jails # iocage list
+-----+----------+-------+-----+--------------+-------------+
| JID |   UUID   | STATE | TAG |   RELEASE    |     IP4     |
+=====+==========+=======+=====+==============+=============+
| 1   | 9dc087fe | up    | tom | 11.0-RELEASE | 10.0.10.200 |
+-----+----------+-------+-----+--------------+-------------+
[webhotell_env] root@firestar:/iocage/jails # ls
9dc087fe-a3c5-43f0-970e-9cc26e2ebb1a

[webhotell_env] root@firestar:/iocage/jails # iocage create -b -r 11.0-RELEASE -u 743f1941-20e2-4df5-abf5-e4138d823ba6 tag=backup ip6_addr="re0|2001:4648:1c88:0:f4b0:b3c3:3789:2a26" host_hostname=backup.p.no boot=on

  tag: "backup" in use by 743f1941-20e2-4df5-abf5-e4138d823ba6!
  Renaming 743f1941-20e2-4df5-abf5-e4138d823ba6's tag to 2017-05-11@09:22:08:137637.

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 85, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 126, in create_cmd
    basejail=basejail, empty=empty).create_jail()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 191, in create_jail
    "ro", "0", "0", silent=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 36, in __init__
    self.__fstab_parse__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 44, in __fstab_parse__
    self.__fstab_add__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 56, in __fstab_add__
    with open(f"{self.uuid}/jails/{self.uuid}/fstab", "r") as fstab:
FileNotFoundError: [Errno 2] No such file or directory: '743f1941-20e2-4df5-abf5-e4138d823ba6/jails/743f1941-20e2-4df5-abf5-e4138d823ba6/fstab'
[webhotell_env] root@firestar:/iocage/jails # ls
743f1941-20e2-4df5-abf5-e4138d823ba6    9dc087fe-a3c5-43f0-970e-9cc26e2ebb1a
[webhotell_env] root@firestar:/iocage/jails # ls 743f1941-20e2-4df5-abf5-e4138d823ba6/
config.json     fstab           root

**Comment by kitten77** [comment]
[webhotell_env] root@firestar:/home/muad/iocage # iocage destroy backup
backup not found!

**Comment by skarekrow** [comment]
I believe I fixed this issue a couple days ago. Make sure you update to the latest version on GitHub and try it all again from scratch.

Also please in the future use informative issue titles, this is just the version and nothing about the actual issue in the title :)

**Comment by kitten77** [comment]
[webhotell_env] root@firestar:/home/muad/iocage # git pull
Already up-to-date.

**Comment by skarekrow** [comment]
I'm talking this commit specifically https://github.com/iocage/iocage/commit/7a0c438f5fff38e69d71e1633c967b3d008e5e1a

You can see in your error that you're using old code. As it's not referencing that fixed line. Make sure you remove with pip and reinstall it. The git repo is only one part of the puzzle :)

**Comment by kitten77** [comment]
new too all of this, normally my head is inside the os not in python :) 
i thought git pull && make install . would give me the new code
did a pip3.6 uninstall and then make install . that fixed 

but still getting the tag in use even if iocage list dosent show it

**Comment by skarekrow** [comment]
That is because unfortunately the tag wasn't removed properly. That's also been fixed after this :D 

Just manually remove it from `/iocage/tags/backup`. Yeah the makefile should have worked. Meh. Will have to see what's up there.
